# Site settings
title: Learning to code with Flatiron Learn Verified
header-img: img/home-bg.png
email: tylerdottaylor@gmail.com
copyright_name: TylerTaylor
description: > # this means to ignore newlines until "baseurl:"
  Follow my journey!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  TylerTaylor
learn_profile: TylerTaylor
email_username: tylerdottaylor@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
